name: Build Docker

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout backend
        uses: actions/checkout@v4
        with:
          path: backend

      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/webclient
          path: frontend

      - name: Build UI
        run: |
          cd frontend
          yarn install --frozen-lockfile
          yarn build
          mkdir -p /tmp/client
          cp -r dist/* /tmp/client/
          cd /tmp
          zip -r $GITHUB_WORKSPACE/backend/src/swingmusic/client.zip client

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Name
        id: lowercase
        run: echo "repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.repo }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
